### ISSUE TITLE
Lubuntu 22.04

### ISSUE THREAD

**Issue by sannacho** [migasfree/migasfree-play#11]
Hola. Estamos probando migasfree-play en Lubuntu 22.04 para sustituir ya al migasfree-launcher, pero detectamos un error y no arranca (por lo menos el entorno gráfico). Si lo lanzamos por consola (sudo migasfree-play sync) nos muestra:
...Erroes de Font:
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
.....
[12389:12389:1219/115337.266173:ERROR:gpu_process_transport_factory.cc(1022)] Lost UI shared context.
[12389:12428:1219/115337.307106:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[12389:12389:1219/115339.407155:ERROR:latency_info.cc(164)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big.

Alguna idea?

**Comment by sannacho** [comment]
De hecho el proceso se lanza, el problema es que no aparece nada en pantalla. Seguimos usando xorg, no hemos pasado a wayland:

usuario@nacho-lubu22:~$ ps -elf | grep migasfree
4 S root       57698   57567  0  80   0 -  4930 -      01:23 ?        00:00:00 /usr/bin/sudo /usr/bin/migasfree-play sync
4 S root       57700   57698  0  80   0 -  3877 -      01:23 ?        00:00:00 /bin/bash /usr/bin/migasfree-play sync
4 S root       57811   57700 10  80   0 - 407500 -     01:23 ?        00:00:00 /usr/share/migasfree-play/nwjs/nw /usr/share/migasfree-play sync
4 S root       57820   57811  0  80   0 - 50116 -      01:23 ?        00:00:00 /usr/share/migasfree-play/nwjs/nw --type=zygote --enable-logging --enable-crash-reporter=, --user-data-dir=/root/.config/migasfree-play --nwapp-path=/usr/share/migasfree-play
4 S root       57904   57811 15  80   0 - 436568 -     01:23 ?        00:00:00 /proc/self/exe --type=renderer --enable-logging --no-sandbox --no-zygote --field-trial-handle=110350696621726548,2519800585636613578,131072 --disable-gpu-compositing --service-pipe-token=********************** --lang=es --enable-crash-reporter=, --user-data-dir=/root/.config/migasfree-play --nwapp-path=/usr/share/migasfree-play --nwjs --extension-process --disable-client-side-phishing-detection --enable-offline-auto-reload --enable-offline-auto-reload-visible-only --blink-settings=cssExternalScannerNoPreload=false,cssExternalScannerPreload=true --num-raster-threads=1 --enable-checker-imaging --service-request-channel-token=******************************* --renderer-client-id=2 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
4 S root       57910   57811  0  80   0 - 160351 -     01:23 ?        00:00:00 /proc/self/exe --type=gpu-process --field-trial-handle=110350696621726548,2519800585636613578,131072 --enable-logging --no-sandbox --enable-crash-reporter=, --user-data-dir=/root/.config/migasfree-play --nwapp-path=/usr/share/migasfree-play --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --enable-crash-reporter=, --user-data-dir=/root/.config/migasfree-play --nwapp-path=/usr/share/migasfree-play --enable-logging --service-request-channel-token=*********************************************

**Comment by agacias** [comment]
Habría que buscar por este error: 
ERROR:latency_info.cc(164)] Surface::TakeLatencyInfoFromFrame, LatencyInfo vector size 101 is too big

¿El token lo has puesto verdad?

De todas maneras prueba a borrar el directorio `/root/.config/migasfree-play `

**Comment by sannacho** [comment]
El token es correcto...los he puesto con ***** por evitar ponerlo público.
He subido por si acaso el tamaño de la memoria de vídeo, pero sigo teniendo el problema parecido: el play arranca pero no muestra nada....es decir, mantiene los errores anteriores, que igual no son problemáticos:
[1904:1904:1220/182838.725390:ERROR:gpu_process_transport_factory.cc(1022)] Lost UI shared context.
[1904:1931:1220/182838.872487:ERROR:bus.cc(394)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix"

Pero no se muestra la ventana,ni apareceen el área de nortificaciones...

**Comment by jact** [comment]
La razón por la que no arranca el interfaz de Migasfree Play en Lubuntu 22.04 es porque Lubuntu tiene un nuevo entorno gráfico: **lxqt-session**, que reemplaza a **lxsession**.

El reconocimiento del entorno gráfico se encuentra en la función **get_graphic_pid** en el fichero **utils.py** de **migasfree-client**.

Como no se detecta el entorno gráfico, al intentar obtener la lista de paquetes del equipo desde Migasfree Play, se obtiene una cadena de error en lugar de sólo una lista de paquetes y por eso no arranca el interfaz de la aplicación.
